/* test16colors.c - A.A.Shabarshin (April 2015) */

#include <stdio.h>
#include <math.h>

#define RGB(r,g,b) (r|(g<<8)|(b<<16))

unsigned long actual[16] = {
 RGB(  4,   4,  12),
 RGB(  1,  19, 159),
 RGB( 70,   2, 172),
 RGB(  1,  86, 255),
 RGB(102,  15,  15),
 RGB(122, 133, 137),
 RGB(249,  49, 131),
 RGB(219, 118, 254),
 RGB(  0,  99,  34),
 RGB(  1, 207, 133),
 RGB(127, 133, 125),
 RGB( 15, 188, 253),
 RGB(138, 185,  54),
 RGB(102, 253,  90),
 RGB(253, 182,  74),
 RGB(220, 217, 202),
};

/*

 Palette to visualize Mandelbrot set (19 colors) as generated by this program:

 E[0]    #00
 E[8]    #40
 E[20]   #44
 E[45]   #64
 E[74]   #E4
 E[89]   #C4
 E[99]   #D4
 E[102]  #C8
 E[112]  #D8
 E[141]  #98
 E[156]  #B8
 E[160]  #91
 E[166]  #83
 E[173]  #31
 E[191]  #32
 E[209]  #73
 E[224]  #B7
 E[235]  #F7
 E[245]  #FF

*/

int main()
{
 int i,j,me,mj,r,g,b;
 double d,c1,c2;

 for(i=0;i<256;i++)
 {
   me = 1000;
   mj = -1;
   for(j=0;j<256;j++)
   {
      d = 0;
      c1 = ((actual[j&15]&255)+(actual[j>>4]&255))/2.0;
      r = c1; if(c1-r>=0.5) r++; if(r>255) r=255;
      if(i<64) c2=255.0*i/63;
      else if(i<128) c2=255.0*(127-i)/63;
      else if(i<192) c2=0;
      else c2=255.0*(i-192)/63;
      d += (c1-c2)*(c1-c2);
      c1 = (((actual[j&15]>>8)&255)+((actual[j>>4]>>8)&255))/2.0;
      g = c1; if(c1-g>=0.5) g++; if(g>255) g=255;
      if(i<64) c2=0;
      else if(i<128) c2=255.0*(i-64)/63;
      else if(i<192) c2=255.0*(191-i)/63;
      else c2=255.0*(i-192)/63;
      d += (c1-c2)*(c1-c2);
      c1 = (((actual[j&15]>>16)&255)+((actual[j>>4]>>16)&255))/2.0;
      b = c1; if(c1-b>=0.5) b++; if(b>255) b=255;
      if(i<128) c2=0;
      else if(i<192) c2=255.0*(i-128)/63;
      else c2=255;
      d += (c1-c2)*(c1-c2);
      d = sqrt(d);
//      printf("%3.2lf\t",d);
      if(d < me)
      {
        me = (int)d;
        if(d-me >= 0.5) me++;
        mj = j;
      }
   }
   if((mj&15) > (mj>>4)) mj=((mj&15)<<4)|(mj>>4);
   printf("E[%i]\t#%2.2X\n",i,mj); // me
 }

 return 0;
}
